# Generated by Django 3.1.4 on 2020-12-31 00:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eventForm',
            fields=[
                ('eventId', models.AutoField(primary_key=True, serialize=False)),
                ('eventName', models.TextField(max_length=60)),
                ('eventDate', models.DateField()),
                ('eventStartTime', models.TimeField()),
                ('eventEndTime', models.TimeField()),
                ('eventNotes', models.TextField(max_length=300)),
                ('eventCreation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
